driver:
  name: dokken
  chef_version: 12.5.1

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  root_path: '/opt/verifier'
  sudo: false

platforms:
- name: centos-5
  driver:
    image: centos:5

- name: centos-6
  driver:
    image: centos:6

- name: centos-7
  driver:
    image: centos:7

suites:
- name: remi
  run_list:
  - recipe[yum-remi-chef::remi]
  attributes:
    yum:
      remi:
        enabled: true
        managed: true

- name: remi-php55
  run_list:
  - recipe[yum-remi-chef::remi-php55]
  attributes:
    yum:
      remi:
        enabled: true
        managed: true
      remi-php55:
        enabled: true
        managed: true

- name: remi-php56
  run_list:
  - recipe[yum-remi-chef::remi-php56]
  attributes:
    yum:
      remi:
        enabled: true
        managed: true
      remi-php56:
        enabled: true
        managed: true

- name: remi-php70
  run_list:
  - recipe[yum-remi-chef::remi-php70]
  attributes:
    yum:
      remi:
        enabled: true
        managed: true
      remi-php70:
        enabled: true
        managed: true
